package com.project.picpicker

object LibsVersion {
    const val hiltVersion = "2.42"
    const val coreVersion = "1.8.0"
    const val kotlinVersion = "1.6.20"
    const val composeVersion = "1.2.0-beta03"
    const val systemUiControllerVersion = "0.24.10-beta"
    const val accompanistNavigationVersion = "0.24.10-beta"
    const val navigationComposeVersion = "2.5.0-rc01"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val timberVersion = "5.0.1"
    const val activityComposeVersion = "1.6.0-alpha03"
    const val customViewPoolingcontainerVersion = "1.0.0-beta02"
    const val uiToolingVersion = "1.2.0-beta03"
    const val customViewVersion = "1.2.0-alpha01"
    const val retrofitVersion = "2.9.0"
    const val okhttpVersion = "4.9.3"
    const val glideVersion = "4.13.2"
    const val pagerVersion = "0.24.10-beta"
    const val leakcanaryVersion = "2.9.1"
    const val appComponentVersion = "1.6.0-alpha04"
    const val materialVersion = "1.7.0-alpha02"
    const val testVersion = "5.8.2"
}