name: update_lib_version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  updateLibrary:
    name: Run update library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update library
        run: ./gradlew app:updateCatalog
